'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { AppShell } from '../../components/AppShell';
import { AIContentBlock } from '../../components/AIContentBlock';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../lib/api';
import { formatDate } from '../../lib/utils';
import { Sparkles } from 'lucide-react';

export function AIDraftsPage() {
  const { role } = useAuth();
  const [drafts, setDrafts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');

  const fetchDrafts = async () => {
    setLoading(true);
    try {
      const data = await api.getDrafts({
        status: statusFilter,
        type: typeFilter,
      });
      setDrafts(data || []);
    } catch (err) {
      console.error('Error fetching AI drafts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDrafts();
  }, [statusFilter, typeFilter]);

  return (
    <AppShell>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 smooth-card">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-xl font-black text-[#0F172A] tracking-tight">
                AI Drafts Inbox &amp; Review Queue
              </h1>
              <span className="px-3 py-1 rounded-full text-xs font-bold bg-[#F5F3FA] text-[#483473] border border-[#DDD6FE]">
                Human-in-the-Loop
              </span>
            </div>
            <p className="text-xs text-[#526071] font-medium mt-1">
              Review, edit, approve, and track retention outreach and account summaries generated by the OpenRouter AI Copilot.
            </p>
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center justify-between gap-3 p-4 smooth-card">
          <div className="flex items-center gap-2 overflow-x-auto">
            <span className="text-xs text-[#526071] font-bold uppercase hidden sm:inline">Status:</span>
            {[
              { id: '', label: 'All Drafts' },
              { id: 'pending_review', label: 'Pending Review' },
              { id: 'approved', label: 'Approved' },
              { id: 'edited', label: 'Edited' },
              { id: 'sent', label: 'Sent' },
              { id: 'rejected', label: 'Rejected' },
            ].map((st) => (
              <button
                key={st.id}
                onClick={() => setStatusFilter(st.id)}
                className={`px-3 py-1.5 text-xs font-bold rounded-xl transition-all cursor-pointer ${
                  statusFilter === st.id
                    ? 'bg-[#5F4B8B] text-white shadow-2xs'
                    : 'bg-white text-[#526071] hover:text-[#0F172A] border border-slate-200/80 hover:bg-slate-50'
                }`}
              >
                {st.label}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2">
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="text-xs p-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-[#0F4C81]/20 focus:border-[#0F4C81] focus:outline-none bg-white font-semibold text-[#0F172A] cursor-pointer"
            >
              <option value="">All Types</option>
              <option value="retention_message">Retention Outreach</option>
              <option value="onboarding_message">Onboarding Message</option>
              <option value="risk_explanation">Risk Explanation</option>
              <option value="summary">Account Summary</option>
            </select>
          </div>
        </div>

        {/* Drafts Feed */}
        <div className="space-y-4">
          {loading ? (
            <div className="py-16 text-center text-xs text-[#526071] font-semibold">Loading AI drafts queue...</div>
          ) : drafts.length === 0 ? (
            <div className="smooth-card p-12 text-center space-y-3">
              <Sparkles className="w-8 h-8 text-[#5F4B8B] mx-auto animate-pulse" />
              <h3 className="text-sm font-black text-[#0F172A]">No Drafts Found</h3>
              <p className="text-xs text-[#526071] max-w-sm mx-auto font-medium">
                No AI-generated content matching your current filter. Trigger a retention draft from the Renewal Pipeline or Customer Profile!
              </p>
              <Link
                href="/renewals"
                className="inline-block px-4 py-2 text-xs smooth-btn-primary mt-2"
              >
                Go to Renewal Pipeline
              </Link>
            </div>
          ) : (
            drafts.map((draft) => (
              <div key={draft._id} className="space-y-2">
                <div className="flex items-center justify-between px-1">
                  <div className="flex items-center gap-2">
                    <Link
                      href={`/customers/${draft.customerId?._id}`}
                      className="text-xs font-bold text-[#0F172A] hover:text-[#0F4C81] transition-colors"
                    >
                      {draft.customerId?.name || 'Account'}
                    </Link>
                    <span className="text-[11px] text-[#526071] font-medium">• Created {formatDate(draft.createdAt)}</span>
                  </div>
                </div>

                <AIContentBlock
                  draft={draft}
                  onStatusChange={fetchDrafts}
                />
              </div>
            ))
          )}
        </div>
      </div>
    </AppShell>
  );
}

export default AIDraftsPage;
